server:
  port: 8081
  servlet:
    context-path: /catalog

spring:
  application:
    name: catalog-service
  profile:
    active: local

  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: catalog_service_user
    password: catalog_service_password
    driverClassName: org.postgresql.Driver
    schema: catalog
  jpa:
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.PostgreSQL95Dialect
    show-sql: true

  liquibase:
    enabled: false
    user: postgres
    roleName: catalog_service_role
    password: password
